language: node_js

node_js:
  - stable

branches:
  only:
    - master

services:
  - docker

before_install:
  # - docker build -t "travis" .
  # - docker run -d -p 8080:8080 travis
  - docker-compose up -d
  - docker ps -a

deploy:
  provider: heroku
  api_key:
    secure: "ec71be40-7af2-469a-8e32-7bb8c2e80c0b"

  
# script:
#   - npm start