language: node_js

node_js:
  - stable

branches:
  only:
    - master

services:
  - docker

before_install:
  # - docker build -t "travis" .
  # - docker run -d -p 8080:8080 travis
  - docker-compose up
  - docker ps -a
  
# script:
#   - npm start