language: node_js

node_js:
  - stable

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker pull node:11.6.0-alpine
  - docker build -t travis-img .
  - docker run -d -p 8080:8080 travis-img
  - docker ps -a
  
script:
  - npm start