language: node_js
node_js:
- stable
branches:
  only:
  - master
services:
- docker
before_install:
- docker-compose up -d
- docker ps -a
deploy:
  provider: heroku
  api_key:
    secure: XK6f5TpSnq59qHNC5XW/EiSXP6VfEsWR3mwpzv/BPacMiXbFr054Okz2NoVubnDa3ESmKacyuvmxVqORkqQlE+NgcfbqDE3Y7HerpWzwrLXclxccx9YpireSdNaeCwPGiG8pGSzCID85WT3l9WGg87H7cDx/QfTNPnzrUxy4Z5byNSQcCYzsgzyJ04SQPAgIQ+tS42/b2RfzIAgjs03eJh/7zBoG2cWuWzOGa/obyB/BeEdeF7yyQzM88z6uX8cpp91MMBs1ysYBnbmEU+ytayabL4GdIy2MSAZr/KRsFr4E+MWmQ1cBWmU3b2t3Mr8UGej75izhWGez74MaddpQ7UPPiSuONNDyxJJGKSdQCzRMFY3v7rvGBXbqv/XfBPj7a4zYwEjqPf4EqeR1YW+JQZpu2tccAS26QMx86WmrkbIRKPX0U7YXXsQZSVDN99A7GH5E/WkHIWDTfRHhVloRy629bn7LGlRYcwjCI4wC5WrHZQZ1Eh8hj2OY/ADu9GxG3dGmKqlQ7V4U5MMWUMdolDFdM4x36Jawrv2m9YDSR8+04ONUglWgj3FnpB/T3YuM8XGWe4+5VUhrKcypGp5FHkBwVyqfxImNJhbZh6MXorirg6IpkEIax6qj8f7APRCMaMobZ1qVPHqYW0pe1FTZcTuod/MPxo9AzGuYUzadhdU=
  app: calm-ridge-41028
  on:
    repo: Atlas07/travis
